"""Custom recognizer generated by Purview Analyser."""
from typing import List, Optional, Tuple
from presidio_analyzer import PatternRecognizer, Pattern
from presidio_analyzer import EntityRecognizer


class AuBsbStgRecognizer(PatternRecognizer):
    """
    Recognizes St George Bank-State-Branch ("BSB") number.

In Australia, a BSB (Bank-State-Branch) is a 6 digit code which identifies a financial institution and branch, detected formats XXX-XXX, XX XXXX, XXXXXX, XXX XXX.

St George  BSBs were sourced from AusPayNet BSB guidelines.

This recognizer identifies  St George  BSB using regex and context words.
Reference (official lookup): https://bsb.auspaynet.com.au/
Reference (BSB system overview / downloads): https://auspaynet.com.au/BSBLinks
    """

    PATTERNS = [
        Pattern(
            "BSB StGeorge (medium)",
            r"\b(?:112[ -]?(?:10(?:0|5)|11[2-3]|12[1-2]|25(?:0|1|2|4|5|8)|265|280|300|331|598|701|74[4-6]|801|861|879|89[5-6]|90[2-4]|90[6-8]|91(?:1|2|4)|92[1-4]|927|931|93[3-4]|998)|113[ -]?(?:100|25[0-1]|258|598|701|78[6-9]|801|879|90[2-4]|90[6-8]|911|914|921|957|975|998)|114[ -]?(?:10[0-3]|25[0-1]|258|598|701|801|879|90[2-4]|906|907|911|914|921|998)|115[ -]?(?:10[0-2]|25[0-1]|258|565|598|701|879|90[2-4]|90[6-8]|911|914|92[1-4]|927|931|934|998)|116[ -]?(?:10[0-3]|25[0-1]|258|598|879|90[2-4]|906|907|911|914|921|998)|117[ -]?(?:598|904|907|911|914|921|978)|118[ -]?(?:904|907|911|914|921)|119[ -]?(?:598|90(?:4|6|7)|911|914|92(?:0|1))|330[ -]?0(?:33|4[0-2]|44)|332[ -]?(?:00[1-3]|005|01[1-3]|015|01[89]|020|022|0(?:2[5-9]|30|3[3-5]|37|4[4-5]|5[0-6]|58|67|7[1-2]|8[2-4]|86|89|9[0-9])|10[0-3]|11[3-5]|118|127|18[2-5]|192|20[1-3]|205|212|291|392|40(?:1|3|7|8|9)|50[1-3]|50[7-9]|527|60(?:1|3|7|8|9)|800|862|901|903|90[7-9])|333[ -]?(?:013|025|030|032|035|03[7-9]|04[6-7]|053|055|073|113|125|133|13[7-8]|147|153|203|213|30[1-3]|30[7-9]|393|70(?:1|3|7|8|9)|800|845)|334[ -]?(?:005|013|014|018|024|025|027|030|037|040|041|056|057|060|074|082|084|085|086|092|105|113|140|204|214|394|40[1-3]|40[7-9]|800)|335[ -]?(?:050|100|205|215|501)|336[ -]?(?:013|025|057|060|06[1-6]|068|076|095|10[1-6]|113|120|160|206|216|396|60[1-3]|800))\b",
            1.0,
        ),
    ]

    CONTEXT = [
        "StGeorge",
        "bsb",
    ]

    def __init__(
        self,
        patterns: Optional[List[Pattern]] = None,
        context: Optional[List[str]] = None,
        supported_language: str = "en",
        supported_entity: str = "AU_BSB_STG",
        replacement_pairs: Optional[List[Tuple[str, str]]] = None,
        name: Optional[str] = None,
    ):
        self.replacement_pairs = (
            replacement_pairs if replacement_pairs else [("-", ""), (" ", "")]
        )
        patterns = patterns if patterns else self.PATTERNS
        context = context if context else self.CONTEXT
        super().__init__(
            supported_entity=supported_entity,
            patterns=patterns,
            context=context,
            supported_language=supported_language,
            name=name or "au_bsb_stg_recognizer",
        )

    def validate_result(self, pattern_text: str) -> bool:
        """Optional post-regex validation hook. Override if checksum is needed."""
        _ = EntityRecognizer.sanitize_value(pattern_text, self.replacement_pairs)
        return True
