"""Custom recognizer generated by Purview Analyser."""
from typing import List, Optional, Tuple
from presidio_analyzer import PatternRecognizer, Pattern
from presidio_analyzer import EntityRecognizer


class AuPassportRecognizer(PatternRecognizer):
    """
    Australian Passport / Travel Document Number (Contextual)

Detects an Australian passport/travel document number only when “passport” or “document” appears nearby (high-precision, lower false positives).

Match rule
	•	Requires keyword: passport or document (case-insensitive)
	•	Within 200 characters of the keyword, matches:
E or PA–PE or RA or N or M + 7 digits
	•	Uses (?!\d) so the 7 digits aren’t followed by another digit
	•	Wrapped with delimiter/start/end boundaries to avoid matching inside other tokens
	•	Supports keyword either before or after the number (OCR/layout-safe)
    """

    PATTERNS = [
        Pattern(
            "AUS Passport (medium)",
            r"(((?i:(?:passport|document)\b[\s\S]{0,200}?(?:E|P[A-E]|RA|N|M)\d{7}(?!\d)|((?:E|P[A-E])|RA|N|M)\d{7}(?!\d)[\s\S]{0,200}?\b(?:passport|document))))",
            0.1,
        ),
    ]

    CONTEXT = [
        "passport",
        "document",
        "Australia",
        "exp",
    ]

    def __init__(
        self,
        patterns: Optional[List[Pattern]] = None,
        context: Optional[List[str]] = None,
        supported_language: str = "en",
        supported_entity: str = "AU_PASSPORT",
        replacement_pairs: Optional[List[Tuple[str, str]]] = None,
        name: Optional[str] = None,
    ):
        self.replacement_pairs = (
            replacement_pairs if replacement_pairs else [("-", ""), (" ", "")]
        )
        patterns = patterns if patterns else self.PATTERNS
        context = context if context else self.CONTEXT
        super().__init__(
            supported_entity=supported_entity,
            patterns=patterns,
            context=context,
            supported_language=supported_language,
            name=name or "au_passport_recognizer",
        )

    def validate_result(self, pattern_text: str) -> bool:
        """Optional post-regex validation hook. Override if checksum is needed."""
        _ = EntityRecognizer.sanitize_value(pattern_text, self.replacement_pairs)
        return True
